---
_extends: .github

repository:
  name: ci-tools
  description: Common tools for building TokTok repositories on CI
  topics: haskell, ci

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - "code-review/reviewable"
