---
language: generic
os: linux

cache:
  directories:
    - "$HOME/.stack"

script:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --no-terminal install hlint pandoc stylish-haskell happy
  - travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-7.10.3.tar.bz2 | tar -xj -C $HOME/.local/bin
  - cp -a bin $HOME/.local/
  # TODO(iphydf): Figure out how to do this more generically. How were we supposed
  # to know that this file is needed and can be found here?
  - cp $HOME/.stack/snapshots/x86_64-linux/*/8.8.2/share/x86_64-linux-ghc-8.8.2/hlint-2.2.11/hlint.yaml $HOME/.local/bin/data/
  - (WORK=`pwd` && cd $HOME && tar zcf $WORK/hs-tools-$TRAVIS_TAG.tar.gz -C $HOME
      .local/bin
      .stack/snapshots/x86_64-linux/*/8.8.2/share/x86_64-linux-ghc-8.8.2/happy-1.19.12
      .stack/snapshots/x86_64-linux/*/8.8.2/share/x86_64-linux-ghc-8.8.2/hlint-2.2.11
      .stack/snapshots/x86_64-linux/*/8.8.2/share/x86_64-linux-ghc-8.8.2/pandoc-2.9.1.1)

deploy:
  provider: releases
  token:
    secure: wpWQHYh3KFfrHdWf3TjPX0E/Y6PDRO+rWaw1T6cBvq0VYktmkY7f6FrIgxoHvYyIiHNHtbRPzBIvNhgEcnv95kjWKWlrlEOKppzRvS0DKxYERMtJIvJaEKx9CXTObErXh0DCdcA9GqmmCUNgu7dHNPUG96oGUAQRy1widxYNcIGM52R/pi2JZIiWbCZBG1YB+Odxt6KmPmKTw3De68GKK450/fApqaQGoBWpgD427YjbM68ZFnPS3zK3AZ9GHg3r0xvXuX9fVZ8JD0y5DBTCKWmlDhQuP7Ib50HM71HgnbDniefLpX2pSc9ic26Ij3hiUzi2zj9Uk28qyu4r5RUJwauJ52pVp/r5Ooc7pnF+JTh4tAMlxXsl841NZW4RB/UoS3zXH69JZ4VWWhoMuJDu7DUqaM8BGeICqGJvaklLk9fMBOiAbYhUxY+PvU9hm4zDy2sTB+o3H1Tumlkc5RsZTxyUTHVxgfczzzwXqesfoR1ivZcXgQy/yAUGqdOyoqNwLxbUJQfFbOw/HYS56rVxYPu5qJXInb8nvNwuKbjteV9pIhxgDdRCznvjLLw5xcMmHg7opDBZ/iNmVTxTVERsYRl6fViI7NGUlSodgzNbpp/mBDeDCU7THJ4mR2UvG4jASiJLD3Gr5Il6K6pB9e6JHLV+ZZ8tVzJcXreaP4wm5dc=
  file: hs-tools-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    repo: TokTok/hs-tools
    tags: true
