name: common-ci

on: [workflow_call]

jobs:
  buildifier:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install
        run: |
          BUILDIFIER_URL=https://github.com/bazelbuild/buildtools/releases/download/v7.3.1/buildifier-linux-amd64
          wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 3 -O buildifier "$BUILDIFIER_URL"
          chmod +x buildifier
      - name: Check
        run: ./buildifier --lint=warn --warnings=all -mode diff $(find . -type f -name "WORKSPACE" -or -name "BUILD.*" -or -name "*.BUILD" -or -name "*.bazel")

  restyled:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: restyled-io/actions/setup@v4
      - id: restyler
        uses: restyled-io/actions/run@v4

      - name: Copy patch to staged artifact
        if: ${{ steps.restyler.outputs.git-patch }}
        run: |
          cat >>/tmp/restyled.diff <<'EOM'
          ${{ steps.restyler.outputs.git-patch }}
          EOM

      - id: upload
        uses: actions/upload-artifact@v4
        with:
          path: /tmp/restyled.diff
          if-no-files-found: ignore
          overwrite: true

      - name: Print patch instructions
        if: ${{ steps.upload.outputs.artifact-url }}
        run: |
          cat >>"$GITHUB_STEP_SUMMARY" <<'EOM'
          ## Restyled

          To apply these fixes locally, either:

              Download '${{ steps.upload.outputs.artifact-url }}' with the web browser
              $ cat restyled.diff.zip | unzip -p - restyled.diff | git am

          Or use the [hub-restyled](https://github.com/TokTok/hs-github-tools/blob/master/tools/hub-restyled) tool:

              $ hub-restyled

          EOM
          exit 1
