name: release

on:
  push:
    branches: [master]
  pull_request_target:
    branches: [master]
    types: [opened, reopened, synchronize]

jobs:
  release:
    uses: ./.github/workflows/release-drafter.yml

  netlify:
    uses: ./.github/workflows/netlify.yml
    with:
      dockerfile: platform/wasm/wasm.Dockerfile
      path: /qtox
    secrets:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
