on:
  workflow_call:

jobs:
  build-cabal:
    name: Cabal Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.6.2.0"]
        ghc: ["9.2.1"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: cache-cabal
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-${{ env.cache-name }}-
            ${{ runner.os }}-${{ matrix.ghc }}-
            ${{ runner.os }}-

      - name: Install non-Haskell dependencies
        run: if [ -f tools/prepare_third_party.sh ]; then tools/prepare_third_party.sh; fi
      - name: Run tests
        run: cabal test --enable-doc all

  build-stack:
    name: Stack Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["latest"]
        ghc: ["9.2.1"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: ${{ matrix.stack }}

      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: cache-stack
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-${{ env.cache-name }}-
            ${{ runner.os }}-${{ matrix.ghc }}-
            ${{ runner.os }}-

      - name: Install non-Haskell dependencies
        run: if [ -f tools/prepare_third_party.sh ]; then tools/prepare_third_party.sh; fi
      - name: Run tests
        run: stack test
