on: [workflow_call]

jobs:
  stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run:
          docker run --rm
            -v "$PWD:/work/${{ github.event.repository.name }}"
            "$IMAGE"
            stack build "echo ${{ github.event.repository.name }} | sed -e 's/^hs-//'"
