on:
  workflow_call:
    inputs:
      ghc-version:
        required: false
        type: string
        default: "8.10.3"
      cabal-version:
        required: false
        type: string
        default: "3.4"
    secrets:
      API_TOKEN_HACKAGE:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: .github/docker/Dockerfile
          push: true
          tags: toxchat/haskell:${{ github.event.repository.name }}
          cache-from: type=registry,ref=toxchat/haskell:${{ github.event.repository.name }}-buildcache
          cache-to: type=registry,ref=toxchat/haskell:${{ github.event.repository.name }}-buildcache,mode=max

  hackage:
    name: Publish to Hackage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout TokTok/ci-tools
        uses: actions/checkout@v2
        with:
          repository: TokTok/ci-tools
          path: ci-tools

      - uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ inputs.ghc-version }}
          cabal-version: ${{ inputs.cabal-version }}

      - name: Cache
        uses: actions/cache@v2
        env:
          ghc-version: ${{ inputs.ghc-version }}
          cache-name: cache-cabal
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ env.ghc-version }}-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.ghc-version }}-${{ env.cache-name }}-
            ${{ runner.os }}-${{ env.ghc-version }}-

      - name: Build haddock documentation
        run: cabal update && cabal haddock --haddock-for-hackage --enable-doc

      - name: Publish package candidate to Hackage
        if: ${{ github.event_name == 'push' }}
        env:
          API_TOKEN_HACKAGE: ${{ secrets.API_TOKEN_HACKAGE }}
        run: $GITHUB_WORKSPACE/ci-tools/bin/hackage_upload candidate

      - name: Publish package to Hackage
        if: ${{ github.event_name == 'release' }}
        env:
          API_TOKEN_HACKAGE: ${{ secrets.API_TOKEN_HACKAGE }}
        run: $GITHUB_WORKSPACE/ci-tools/bin/hackage_upload
