on: [workflow_call]

jobs:
  stack:
    runs-on: ubuntu-latest
    container: toxchat/toktok-stack:haskell
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: stack build
