on: [workflow_call]

jobs:
  stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          IMAGE=toxchat/haskell:${{ github.event.repository.name }}
          if ! docker pull "$IMAGE"; then
            IMAGE=toxchat/haskell:latest
            docker pull "$IMAGE"
          fi
          docker run --rm -v "$PWD:/work" "$IMAGE" stack build --allow-different-user
