on:
  workflow_call:
    inputs:
      ghc-version:
        required: false
        type: string
        default: "9.2.1"
      cabal-version:
        required: false
        type: string
        default: "3.6.2.0"

jobs:
  cabal:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ inputs.ghc-version }}
          cabal-version: ${{ inputs.cabal-version }}

      - name: Cache
        uses: actions/cache@v2
        env:
          ghc-version: ${{ inputs.ghc-version }}
          cache-name: cache-cabal
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ env.ghc-version }}-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.ghc-version }}-${{ env.cache-name }}-
            ${{ runner.os }}-${{ env.ghc-version }}-
            ${{ runner.os }}-

      - name: Install non-Haskell dependencies
        run: if [ -f tools/prepare_third_party.sh ]; then tools/prepare_third_party.sh; fi
      - name: Run tests
        run: cabal test --enable-doc all

  stack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ inputs.ghc-version }}
          enable-stack: true
          stack-version: "latest"

      - name: Cache
        uses: actions/cache@v2
        env:
          ghc-version: ${{ inputs.ghc-version }}
          cache-name: cache-stack
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-${{ env.ghc-version }}-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.ghc-version }}-${{ env.cache-name }}-
            ${{ runner.os }}-${{ env.ghc-version }}-
            ${{ runner.os }}-

      - name: Install non-Haskell dependencies
        run: if [ -f tools/prepare_third_party.sh ]; then tools/prepare_third_party.sh; fi
      - name: Run tests
        run: stack test
