on: [workflow_call]

jobs:
  stack:
    runs-on: ubuntu-latest
    container: toxchat/haskell
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: stack build "$(echo ${{ github.event.repository.name }} | sed -e 's/^hs-//')"
