on: [workflow_call]

jobs:
  stack:
    runs-on: ubuntu-latest
    container: toxchat/toktok-stack:haskell
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: stack test
      - name: Build source package
        run: stack sdist
