name: release

on:
  issues:
    types: [assigned]

concurrency:
  group: release-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    uses: ./.github/workflows/release-deploy.yml
    with:
      production: true
    secrets:
      TOKEN_RELEASES: ${{ secrets.TOKEN_RELEASES }}
