name: release

on:
  push:
    branches: [master]
  pull_request_target:
    branches: [master]
    types: [opened, reopened, synchronize]

jobs:
  release:
    uses: ./.github/workflows/release-drafter.yml
